---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "http://localhost:9090/job/AnsibleWeb-CICD-Pipeline/1/execution/node/3/ws/target/AnsibleWeb.war"
        dest: "/opt/tomcat/webapps/AnsibleWeb.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
    
