- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    -name: Copy WAR file to Tomcat
     copy:
     src: "/var/snap/jenkins/4874/workspace/AnsibleWeb-CICD-Pipeline/target/MyMavenWebApp.war"
     dest: "/opt/tomcat/webapps/MyMavenWebApp.war"
     remote_src: no
      
    -name: Restart Tomcat
     systemd:
     name: tomcat
     state: restarted
    
